package com.webside.ofp.model;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table customer
 *
 * @mbg.generated do_not_delete_during_merge Tue Jul 18 00:02:59 CST 2017
 */
public class CustomerEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.CUSTOMER_ID
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    private Integer customerId;

    /**
     * Database Column Remarks:
     *   客户名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.CUSTOMER_NAME
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    private String customerName;

    /**
     * Database Column Remarks:
     *   电话
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.TELEPHONE
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    private String telephone;

    /**
     * Database Column Remarks:
     *   国家
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.COUNTRY
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    private String country;

    /**
     * Database Column Remarks:
     *   逻辑删除（1.删除，0，否）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.IS_DELETE
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    private Integer isDelete;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.CREATE_TIME
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   修改时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.MODIFY_TIME
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    private Date modifyTime;

    /**
     * Database Column Remarks:
     *   创建人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.CREATE_USER
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    private Integer createUser;

    /**
     * Database Column Remarks:
     *   修改人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.MDOIFY_USER
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    private Integer modifyUser;

    /**
     * Database Column Remarks:
     *   描述
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.DESCRIPTION
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.CUSTOMER_ID
     *
     * @return the value of customer.CUSTOMER_ID
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    public Integer getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.CUSTOMER_ID
     *
     * @param customerId the value for customer.CUSTOMER_ID
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.CUSTOMER_NAME
     *
     * @return the value of customer.CUSTOMER_NAME
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    public String getCustomerName() {
        return customerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.CUSTOMER_NAME
     *
     * @param customerName the value for customer.CUSTOMER_NAME
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    public void setCustomerName(String customerName) {
        this.customerName = customerName == null ? null : customerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.TELEPHONE
     *
     * @return the value of customer.TELEPHONE
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.TELEPHONE
     *
     * @param telephone the value for customer.TELEPHONE
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.COUNTRY
     *
     * @return the value of customer.COUNTRY
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.COUNTRY
     *
     * @param country the value for customer.COUNTRY
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    public void setCountry(String country) {
        this.country = country == null ? null : country.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.IS_DELETE
     *
     * @return the value of customer.IS_DELETE
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.IS_DELETE
     *
     * @param isDelete the value for customer.IS_DELETE
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.CREATE_TIME
     *
     * @return the value of customer.CREATE_TIME
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.CREATE_TIME
     *
     * @param createTime the value for customer.CREATE_TIME
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.MODIFY_TIME
     *
     * @return the value of customer.MODIFY_TIME
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.MODIFY_TIME
     *
     * @param modifyTime the value for customer.MODIFY_TIME
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.CREATE_USER
     *
     * @return the value of customer.CREATE_USER
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    public Integer getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.CREATE_USER
     *
     * @param createUser the value for customer.CREATE_USER
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    public void setCreateUser(Integer createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.MDOIFY_USER
     *
     * @return the value of customer.MDOIFY_USER
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    public Integer getModifyUser() {
        return modifyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.MDOIFY_USER
     *
     * @param mdoifyUser the value for customer.MDOIFY_USER
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    public void setModifyUser(Integer modifyUser) {
        this.modifyUser = modifyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.DESCRIPTION
     *
     * @return the value of customer.DESCRIPTION
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.DESCRIPTION
     *
     * @param description the value for customer.DESCRIPTION
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}