package com.webside.ofp.model;

/**
 *
 * This class was generated by MyBatis Generator. This class corresponds to the
 * database table interest_rate
 *
 * @mbg.generated do_not_delete_during_merge Tue Jul 18 00:02:59 CST 2017
 */
public class InterestRateEntity {
	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column interest_rate.INTEREST_RATE_ID
	 *
	 * @mbg.generated Tue Jul 18 00:02:59 CST 2017
	 */
	private Integer interestRateId;

	/**
	 * Database Column Remarks: 利率,算利息的
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column interest_rate.RATE
	 *
	 * @mbg.generated Tue Jul 18 00:02:59 CST 2017
	 */
	private double rate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column interest_rate.INTEREST_RATE_ID
	 *
	 * @return the value of interest_rate.INTEREST_RATE_ID
	 *
	 * @mbg.generated Tue Jul 18 00:02:59 CST 2017
	 */
	public Integer getInterestRateId() {
		return interestRateId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column interest_rate.INTEREST_RATE_ID
	 *
	 * @param interestRateId
	 *            the value for interest_rate.INTEREST_RATE_ID
	 *
	 * @mbg.generated Tue Jul 18 00:02:59 CST 2017
	 */
	public void setInterestRateId(Integer interestRateId) {
		this.interestRateId = interestRateId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column interest_rate.RATE
	 *
	 * @return the value of interest_rate.RATE
	 *
	 * @mbg.generated Tue Jul 18 00:02:59 CST 2017
	 */
	public Double getRate() {
		return rate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column interest_rate.RATE
	 *
	 * @param rate
	 *            the value for interest_rate.RATE
	 *
	 * @mbg.generated Tue Jul 18 00:02:59 CST 2017
	 */
	public void setRate(Double rate) {
		this.rate = rate;
	}
}