package com.webside.ofp.model;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table product_type
 *
 * @mbg.generated do_not_delete_during_merge Tue Jul 18 00:02:59 CST 2017
 */
public class ProductTypeEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_type.PRODUCT_TYPE_ID
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    private Integer productTypeId;

    /**
     * Database Column Remarks:
     *   产品类型中文名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_type.CN_NAME
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    private String cnName;

    /**
     * Database Column Remarks:
     *   产品类型英文名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_type.EN_NAME
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    private String enName;

    /**
     * Database Column Remarks:
     *   父类
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_type.PARENT_ID
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    private Integer parentId;

    /**
     * Database Column Remarks:
     *   等级
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_type.LEVEL
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    private Integer level;

    /**
     * Database Column Remarks:
     *   排序
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_type.ORDERBY
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    private Integer orderby;

    /**
     * Database Column Remarks:
     *   逻辑删除（1.删除，0，否）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_type.IS_DELETE
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    private Integer isDelete;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_type.CREATE_TIME
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   修改时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_type.MODIFY_TIME
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    private Date modifyTime;

    /**
     * Database Column Remarks:
     *   创建人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_type.CREATE_USER
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    private Integer createUser;

    /**
     * Database Column Remarks:
     *   修改人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_type.MDOIFY_USER
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    private Integer modifyUser;

    /**
     * Database Column Remarks:
     *   描述
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_type.DESCRIPTION
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_type.PRODUCT_TYPE_ID
     *
     * @return the value of product_type.PRODUCT_TYPE_ID
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    public Integer getProductTypeId() {
        return productTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_type.PRODUCT_TYPE_ID
     *
     * @param productTypeId the value for product_type.PRODUCT_TYPE_ID
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    public void setProductTypeId(Integer productTypeId) {
        this.productTypeId = productTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_type.CN_NAME
     *
     * @return the value of product_type.CN_NAME
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    public String getCnName() {
        return cnName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_type.CN_NAME
     *
     * @param cnName the value for product_type.CN_NAME
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    public void setCnName(String cnName) {
        this.cnName = cnName == null ? null : cnName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_type.EN_NAME
     *
     * @return the value of product_type.EN_NAME
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    public String getEnName() {
        return enName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_type.EN_NAME
     *
     * @param enName the value for product_type.EN_NAME
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    public void setEnName(String enName) {
        this.enName = enName == null ? null : enName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_type.PARENT_ID
     *
     * @return the value of product_type.PARENT_ID
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_type.PARENT_ID
     *
     * @param parentId the value for product_type.PARENT_ID
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_type.LEVEL
     *
     * @return the value of product_type.LEVEL
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_type.LEVEL
     *
     * @param level the value for product_type.LEVEL
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_type.ORDERBY
     *
     * @return the value of product_type.ORDERBY
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    public Integer getOrderby() {
        return orderby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_type.ORDERBY
     *
     * @param orderby the value for product_type.ORDERBY
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    public void setOrderby(Integer orderby) {
        this.orderby = orderby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_type.IS_DELETE
     *
     * @return the value of product_type.IS_DELETE
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_type.IS_DELETE
     *
     * @param isDelete the value for product_type.IS_DELETE
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_type.CREATE_TIME
     *
     * @return the value of product_type.CREATE_TIME
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_type.CREATE_TIME
     *
     * @param createTime the value for product_type.CREATE_TIME
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_type.MODIFY_TIME
     *
     * @return the value of product_type.MODIFY_TIME
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_type.MODIFY_TIME
     *
     * @param modifyTime the value for product_type.MODIFY_TIME
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_type.CREATE_USER
     *
     * @return the value of product_type.CREATE_USER
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    public Integer getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_type.CREATE_USER
     *
     * @param createUser the value for product_type.CREATE_USER
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    public void setCreateUser(Integer createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_type.MDOIFY_USER
     *
     * @return the value of product_type.MDOIFY_USER
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    public Integer getModifyUser() {
        return modifyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_type.MDOIFY_USER
     *
     * @param mdoifyUser the value for product_type.MDOIFY_USER
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    public void setModifyUser(Integer modifyUser) {
        this.modifyUser = modifyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_type.DESCRIPTION
     *
     * @return the value of product_type.DESCRIPTION
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_type.DESCRIPTION
     *
     * @param description the value for product_type.DESCRIPTION
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}