package com.webside.ofp.model;

import java.util.Arrays;

/**
 * Database Table Remarks: 产品表
 *
 * This class was generated by MyBatis Generator. This class corresponds to the
 * database table product
 *
 * @mbg.generated do_not_delete_during_merge Thu Jul 20 23:16:43 CST 2017
 */
public class ProductEntityWithBLOBs extends ProductEntity {
	/**
	 * Database Column Remarks: 缩略图（最大16M）
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column product.THUMBNAIL
	 *
	 * @mbg.generated Thu Jul 20 23:16:43 CST 2017
	 */
	private byte[] thumbnail;

	/**
	 * 附件名称集合
	 */
	private String attachmentNames;

	public String getAttachmentNames() {
		return attachmentNames;
	}

	public void setAttachmentNames(String attachmentNames) {
		this.attachmentNames = attachmentNames;
	}

	/**
	 * Database Column Remarks: 二维码图片
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column product.QR_CODE_PIC
	 *
	 * @mbg.generated Thu Jul 20 23:16:43 CST 2017
	 */
	private byte[] qrCodePic;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column product.THUMBNAIL
	 *
	 * @return the value of product.THUMBNAIL
	 *
	 * @mbg.generated Thu Jul 20 23:16:43 CST 2017
	 */
	public byte[] getThumbnail() {
		return thumbnail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column product.THUMBNAIL
	 *
	 * @param thumbnail
	 *            the value for product.THUMBNAIL
	 *
	 * @mbg.generated Thu Jul 20 23:16:43 CST 2017
	 */
	public void setThumbnail(byte[] thumbnail) {
		this.thumbnail = thumbnail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column product.QR_CODE_PIC
	 *
	 * @return the value of product.QR_CODE_PIC
	 *
	 * @mbg.generated Thu Jul 20 23:16:43 CST 2017
	 */
	public byte[] getQrCodePic() {
		return qrCodePic;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column product.QR_CODE_PIC
	 *
	 * @param qrCodePic
	 *            the value for product.QR_CODE_PIC
	 *
	 * @mbg.generated Thu Jul 20 23:16:43 CST 2017
	 */
	public void setQrCodePic(byte[] qrCodePic) {
		this.qrCodePic = qrCodePic;
	}

	@Override
	public String toString() {
		return super.toString();
	}

}