package com.webside.ofp.model;

import java.math.BigDecimal;
import java.util.Date;

/**
 * Database Table Remarks:
 *   产品表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table product
 *
 * @mbg.generated do_not_delete_during_merge Tue Jul 18 00:02:59 CST 2017
 */
public class ProductEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.PRODUCT_ID
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    private Integer productId;

    /**
     * Database Column Remarks:
     *   产品类型ID,外键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.PRODUCT_TYPE_ID
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    private Integer productTypeId;

    /**
     * Database Column Remarks:
     *   商品编码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.PRODUCT_CODE
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    private String productCode;

    /**
     * Database Column Remarks:
     *   工厂编码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.FACTORY_CODE
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    private String factoryCode;

    /**
     * Database Column Remarks:
     *   单位
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.UNIT
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    private String unit;

    /**
     * Database Column Remarks:
     *   海关编码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.CUSTOMS_CODE
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    private String customsCode;

    /**
     * Database Column Remarks:
     *   美金单价
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.USD_PRICE
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    private BigDecimal usdPrice;

    /**
     * Database Column Remarks:
     *   中文名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.CN_NAME
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    private String cnName;

    /**
     * Database Column Remarks:
     *   英文名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.EN_NAME
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    private String enName;

    /**
     * Database Column Remarks:
     *   增值税率
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.VAT_RATE
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    private Long vatRate;

    /**
     * Database Column Remarks:
     *   收购单价
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.BUY_PRICE
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    private BigDecimal buyPrice;

    /**
     * Database Column Remarks:
     *   重量（单位：g）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.WEIGHT
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    private Integer weight;

    /**
     * Database Column Remarks:
     *   容量（单位：ml）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.VOLUME
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    private Integer volume;

    /**
     * Database Column Remarks:
     *   TOP（单位：mm）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.TOP
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    private Long top;

    /**
     * Database Column Remarks:
     *   BOTTOM（单位：mm）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.BOTTOM
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    private Long bottom;

    /**
     * Database Column Remarks:
     *   HEIGHT(单位：mm)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.HEIGHT
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    private Long height;

    /**
     * Database Column Remarks:
     *   外包装长度（单位:cm）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.LENGTH
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    private Long length;

    /**
     * Database Column Remarks:
     *   外包装宽度（单位：cm）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.WIDTH
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    private Long width;

    /**
     * Database Column Remarks:
     *   外包装高度（单位：cm）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.PACK_HEIGHT
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    private Long packHeight;

    /**
     * Database Column Remarks:
     *   GW
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.GW
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    private Long gw;

    /**
     * Database Column Remarks:
     *   装箱率
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.PACKING_RATE
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    private Long packingRate;

    /**
     * Database Column Remarks:
     *   退税率
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.TAX_REBATE_RATE
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    private Long taxRebateRate;

    /**
     * Database Column Remarks:
     *   CBM
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.CBM
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    private Long cbm;

    /**
     * Database Column Remarks:
     *   包装描述
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.PACKING
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    private String packing;

    /**
     * Database Column Remarks:
     *   产品高清图路径
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.HD_MAP_URL
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    private String hdMapUrl;

    /**
     * Database Column Remarks:
     *   逻辑删除（1.删除，0，否）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.IS_DELETE
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    private Integer isDelete;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.CREATE_TIME
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   修改时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.MODIFY_TIME
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    private Date modifyTime;

    /**
     * Database Column Remarks:
     *   创建人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.CREATE_USER
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    private Integer createUser;

    /**
     * Database Column Remarks:
     *   修改人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.MDOIFY_USER
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    private Integer modifyUser;

    /**
     * Database Column Remarks:
     *   描述
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.DESCRIPTION
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.PRODUCT_ID
     *
     * @return the value of product.PRODUCT_ID
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.PRODUCT_ID
     *
     * @param productId the value for product.PRODUCT_ID
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.PRODUCT_TYPE_ID
     *
     * @return the value of product.PRODUCT_TYPE_ID
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    public Integer getProductTypeId() {
        return productTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.PRODUCT_TYPE_ID
     *
     * @param productTypeId the value for product.PRODUCT_TYPE_ID
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    public void setProductTypeId(Integer productTypeId) {
        this.productTypeId = productTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.PRODUCT_CODE
     *
     * @return the value of product.PRODUCT_CODE
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    public String getProductCode() {
        return productCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.PRODUCT_CODE
     *
     * @param productCode the value for product.PRODUCT_CODE
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    public void setProductCode(String productCode) {
        this.productCode = productCode == null ? null : productCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.FACTORY_CODE
     *
     * @return the value of product.FACTORY_CODE
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    public String getFactoryCode() {
        return factoryCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.FACTORY_CODE
     *
     * @param factoryCode the value for product.FACTORY_CODE
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    public void setFactoryCode(String factoryCode) {
        this.factoryCode = factoryCode == null ? null : factoryCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.UNIT
     *
     * @return the value of product.UNIT
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.UNIT
     *
     * @param unit the value for product.UNIT
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    public void setUnit(String unit) {
        this.unit = unit == null ? null : unit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.CUSTOMS_CODE
     *
     * @return the value of product.CUSTOMS_CODE
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    public String getCustomsCode() {
        return customsCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.CUSTOMS_CODE
     *
     * @param customsCode the value for product.CUSTOMS_CODE
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    public void setCustomsCode(String customsCode) {
        this.customsCode = customsCode == null ? null : customsCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.USD_PRICE
     *
     * @return the value of product.USD_PRICE
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    public BigDecimal getUsdPrice() {
        return usdPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.USD_PRICE
     *
     * @param usdPrice the value for product.USD_PRICE
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    public void setUsdPrice(BigDecimal usdPrice) {
        this.usdPrice = usdPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.CN_NAME
     *
     * @return the value of product.CN_NAME
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    public String getCnName() {
        return cnName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.CN_NAME
     *
     * @param cnName the value for product.CN_NAME
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    public void setCnName(String cnName) {
        this.cnName = cnName == null ? null : cnName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.EN_NAME
     *
     * @return the value of product.EN_NAME
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    public String getEnName() {
        return enName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.EN_NAME
     *
     * @param enName the value for product.EN_NAME
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    public void setEnName(String enName) {
        this.enName = enName == null ? null : enName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.VAT_RATE
     *
     * @return the value of product.VAT_RATE
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    public Long getVatRate() {
        return vatRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.VAT_RATE
     *
     * @param vatRate the value for product.VAT_RATE
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    public void setVatRate(Long vatRate) {
        this.vatRate = vatRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.BUY_PRICE
     *
     * @return the value of product.BUY_PRICE
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    public BigDecimal getBuyPrice() {
        return buyPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.BUY_PRICE
     *
     * @param buyPrice the value for product.BUY_PRICE
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    public void setBuyPrice(BigDecimal buyPrice) {
        this.buyPrice = buyPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.WEIGHT
     *
     * @return the value of product.WEIGHT
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    public Integer getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.WEIGHT
     *
     * @param weight the value for product.WEIGHT
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    public void setWeight(Integer weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.VOLUME
     *
     * @return the value of product.VOLUME
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    public Integer getVolume() {
        return volume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.VOLUME
     *
     * @param volume the value for product.VOLUME
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    public void setVolume(Integer volume) {
        this.volume = volume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.TOP
     *
     * @return the value of product.TOP
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    public Long getTop() {
        return top;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.TOP
     *
     * @param top the value for product.TOP
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    public void setTop(Long top) {
        this.top = top;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.BOTTOM
     *
     * @return the value of product.BOTTOM
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    public Long getBottom() {
        return bottom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.BOTTOM
     *
     * @param bottom the value for product.BOTTOM
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    public void setBottom(Long bottom) {
        this.bottom = bottom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.HEIGHT
     *
     * @return the value of product.HEIGHT
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    public Long getHeight() {
        return height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.HEIGHT
     *
     * @param height the value for product.HEIGHT
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    public void setHeight(Long height) {
        this.height = height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.LENGTH
     *
     * @return the value of product.LENGTH
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    public Long getLength() {
        return length;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.LENGTH
     *
     * @param length the value for product.LENGTH
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    public void setLength(Long length) {
        this.length = length;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.WIDTH
     *
     * @return the value of product.WIDTH
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    public Long getWidth() {
        return width;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.WIDTH
     *
     * @param width the value for product.WIDTH
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    public void setWidth(Long width) {
        this.width = width;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.PACK_HEIGHT
     *
     * @return the value of product.PACK_HEIGHT
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    public Long getPackHeight() {
        return packHeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.PACK_HEIGHT
     *
     * @param packHeight the value for product.PACK_HEIGHT
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    public void setPackHeight(Long packHeight) {
        this.packHeight = packHeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.GW
     *
     * @return the value of product.GW
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    public Long getGw() {
        return gw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.GW
     *
     * @param gw the value for product.GW
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    public void setGw(Long gw) {
        this.gw = gw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.PACKING_RATE
     *
     * @return the value of product.PACKING_RATE
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    public Long getPackingRate() {
        return packingRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.PACKING_RATE
     *
     * @param packingRate the value for product.PACKING_RATE
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    public void setPackingRate(Long packingRate) {
        this.packingRate = packingRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.TAX_REBATE_RATE
     *
     * @return the value of product.TAX_REBATE_RATE
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    public Long getTaxRebateRate() {
        return taxRebateRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.TAX_REBATE_RATE
     *
     * @param taxRebateRate the value for product.TAX_REBATE_RATE
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    public void setTaxRebateRate(Long taxRebateRate) {
        this.taxRebateRate = taxRebateRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.CBM
     *
     * @return the value of product.CBM
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    public Long getCbm() {
        return cbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.CBM
     *
     * @param cbm the value for product.CBM
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    public void setCbm(Long cbm) {
        this.cbm = cbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.PACKING
     *
     * @return the value of product.PACKING
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    public String getPacking() {
        return packing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.PACKING
     *
     * @param packing the value for product.PACKING
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    public void setPacking(String packing) {
        this.packing = packing == null ? null : packing.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.HD_MAP_URL
     *
     * @return the value of product.HD_MAP_URL
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    public String getHdMapUrl() {
        return hdMapUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.HD_MAP_URL
     *
     * @param hdMapUrl the value for product.HD_MAP_URL
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    public void setHdMapUrl(String hdMapUrl) {
        this.hdMapUrl = hdMapUrl == null ? null : hdMapUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.IS_DELETE
     *
     * @return the value of product.IS_DELETE
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.IS_DELETE
     *
     * @param isDelete the value for product.IS_DELETE
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.CREATE_TIME
     *
     * @return the value of product.CREATE_TIME
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.CREATE_TIME
     *
     * @param createTime the value for product.CREATE_TIME
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.MODIFY_TIME
     *
     * @return the value of product.MODIFY_TIME
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.MODIFY_TIME
     *
     * @param modifyTime the value for product.MODIFY_TIME
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.CREATE_USER
     *
     * @return the value of product.CREATE_USER
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    public Integer getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.CREATE_USER
     *
     * @param createUser the value for product.CREATE_USER
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    public void setCreateUser(Integer createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.MDOIFY_USER
     *
     * @return the value of product.MDOIFY_USER
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    public Integer getModifyUser() {
        return modifyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.MDOIFY_USER
     *
     * @param mdoifyUser the value for product.MDOIFY_USER
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    public void setModifyUser(Integer modifyUser) {
        this.modifyUser = modifyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.DESCRIPTION
     *
     * @return the value of product.DESCRIPTION
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.DESCRIPTION
     *
     * @param description the value for product.DESCRIPTION
     *
     * @mbg.generated Tue Jul 18 00:02:59 CST 2017
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}