package com.webside.ofp.model;

import java.math.BigDecimal;

/**
 *
 * This class was generated by MyBatis Generator. This class corresponds to the
 * database table quotation_sub_sheet
 *
 * @mbg.generated do_not_delete_during_merge Tue Jul 18 00:02:59 CST 2017
 */
public class QuotationSubSheetEntity {
	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column quotation_sub_sheet.QUOTATION_SUB_SHEET
	 *
	 * @mbg.generated Tue Jul 18 00:02:59 CST 2017
	 */
	private Integer quotationSubSheetId;

	/**
	 * Database Column Remarks: 产品ID,外键
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column quotation_sub_sheet.PRODUCT_ID
	 *
	 * @mbg.generated Tue Jul 18 00:02:59 CST 2017
	 */
	private Integer productId;

	/**
	 * 产品信息，包含blob类型
	 */
	private ProductEntityWithBLOBs product;

	public ProductEntityWithBLOBs getProduct() {
		return product;
	}

	public void setProduct(ProductEntityWithBLOBs product) {
		this.product = product;
	}

	/**
	 * Database Column Remarks: 报价单ID,外键
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column quotation_sub_sheet.QUOTATION_SHEET_ID
	 *
	 * @mbg.generated Tue Jul 18 00:02:59 CST 2017
	 */
	private Integer quotationSheetId;

	/**
	 * Database Column Remarks: 美金单价
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column quotation_sub_sheet.USD_PRICE
	 *
	 * @mbg.generated Tue Jul 18 00:02:59 CST 2017
	 */
	private Double usdPrice;

	/**
	 * Database Column Remarks: 收购单价
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column quotation_sub_sheet.BUY_PRICE
	 *
	 * @mbg.generated Tue Jul 18 00:02:59 CST 2017
	 */
	private Double buyPrice;

	/**
	 * Database Column Remarks: 单位
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column quotation_sub_sheet.UNIT
	 *
	 * @mbg.generated Tue Jul 18 00:02:59 CST 2017
	 */
	private String unit;

	/**
	 * Database Column Remarks: 重量（单位：g）
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column quotation_sub_sheet.WEIGHT
	 *
	 * @mbg.generated Tue Jul 18 00:02:59 CST 2017
	 */
	private Integer weight;

	/**
	 * Database Column Remarks: 容量（单位：ml）
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column quotation_sub_sheet.VOLUME
	 *
	 * @mbg.generated Tue Jul 18 00:02:59 CST 2017
	 */
	private Integer volume;

	/**
	 * Database Column Remarks: TOP（单位：mm）
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column quotation_sub_sheet.TOP
	 *
	 * @mbg.generated Tue Jul 18 00:02:59 CST 2017
	 */
	private Long top;

	/**
	 * Database Column Remarks: BOTTOM（单位：mm）
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column quotation_sub_sheet.BOTTOM
	 *
	 * @mbg.generated Tue Jul 18 00:02:59 CST 2017
	 */
	private Long bottom;

	/**
	 * Database Column Remarks: HEIGHT(单位：mm)
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column quotation_sub_sheet.HEIGHT
	 *
	 * @mbg.generated Tue Jul 18 00:02:59 CST 2017
	 */
	private Long height;

	/**
	 * Database Column Remarks: PACKING
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column quotation_sub_sheet.PACKING
	 *
	 * @mbg.generated Tue Jul 18 00:02:59 CST 2017
	 */
	private String packing;

	/**
	 * Database Column Remarks: 装箱率
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column quotation_sub_sheet.PACKING_RATE
	 *
	 * @mbg.generated Tue Jul 18 00:02:59 CST 2017
	 */
	private Double packingRate;

	/**
	 * Database Column Remarks: 数量
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column quotation_sub_sheet.NUMBER
	 *
	 * @mbg.generated Tue Jul 18 00:02:59 CST 2017
	 */
	private Integer number;

	/**
	 * Database Column Remarks: 箱数
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column quotation_sub_sheet.PACK_NUM
	 *
	 * @mbg.generated Tue Jul 18 00:02:59 CST 2017
	 */
	private Integer packNum;

	/**
	 * Database Column Remarks: TOTALCBM
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column quotation_sub_sheet.TOTALCBM
	 *
	 * @mbg.generated Tue Jul 18 00:02:59 CST 2017
	 */
	private Double totalcbm;

	/**
	 * Database Column Remarks: GW
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column quotation_sub_sheet.GW
	 *
	 * @mbg.generated Tue Jul 18 00:02:59 CST 2017
	 */
	private Double gw;

	private Double cbm;

	public Double getCbm() {
		return cbm;
	}

	public void setCbm(Double cbm) {
		this.cbm = cbm;
	}

	/**
	 * Database Column Remarks: 总毛重
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column quotation_sub_sheet.TOTAL_GW
	 *
	 * @mbg.generated Tue Jul 18 00:02:59 CST 2017
	 */
	private Double totalGw;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column quotation_sub_sheet.QUOTATION_SUB_SHEET
	 *
	 * @return the value of quotation_sub_sheet.QUOTATION_SUB_SHEET
	 *
	 * @mbg.generated Tue Jul 18 00:02:59 CST 2017
	 */
	public Integer getQuotationSubSheetId() {
		return quotationSubSheetId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column quotation_sub_sheet.QUOTATION_SUB_SHEET
	 *
	 * @param quotationSubSheet
	 *            the value for quotation_sub_sheet.QUOTATION_SUB_SHEET
	 *
	 * @mbg.generated Tue Jul 18 00:02:59 CST 2017
	 */
	public void setQuotationSubSheetId(Integer quotationSubSheetId) {
		this.quotationSubSheetId = quotationSubSheetId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column quotation_sub_sheet.PRODUCT_ID
	 *
	 * @return the value of quotation_sub_sheet.PRODUCT_ID
	 *
	 * @mbg.generated Tue Jul 18 00:02:59 CST 2017
	 */
	public Integer getProductId() {
		return productId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column quotation_sub_sheet.PRODUCT_ID
	 *
	 * @param productId
	 *            the value for quotation_sub_sheet.PRODUCT_ID
	 *
	 * @mbg.generated Tue Jul 18 00:02:59 CST 2017
	 */
	public void setProductId(Integer productId) {
		this.productId = productId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column quotation_sub_sheet.QUOTATION_SHEET_ID
	 *
	 * @return the value of quotation_sub_sheet.QUOTATION_SHEET_ID
	 *
	 * @mbg.generated Tue Jul 18 00:02:59 CST 2017
	 */
	public Integer getQuotationSheetId() {
		return quotationSheetId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column quotation_sub_sheet.QUOTATION_SHEET_ID
	 *
	 * @param quotationSheetId
	 *            the value for quotation_sub_sheet.QUOTATION_SHEET_ID
	 *
	 * @mbg.generated Tue Jul 18 00:02:59 CST 2017
	 */
	public void setQuotationSheetId(Integer quotationSheetId) {
		this.quotationSheetId = quotationSheetId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column quotation_sub_sheet.USD_PRICE
	 *
	 * @return the value of quotation_sub_sheet.USD_PRICE
	 *
	 * @mbg.generated Tue Jul 18 00:02:59 CST 2017
	 */
	public Double getUsdPrice() {
		return usdPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column quotation_sub_sheet.USD_PRICE
	 *
	 * @param usdPrice
	 *            the value for quotation_sub_sheet.USD_PRICE
	 *
	 * @mbg.generated Tue Jul 18 00:02:59 CST 2017
	 */
	public void setUsdPrice(Double usdPrice) {
		this.usdPrice = usdPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column quotation_sub_sheet.BUY_PRICE
	 *
	 * @return the value of quotation_sub_sheet.BUY_PRICE
	 *
	 * @mbg.generated Tue Jul 18 00:02:59 CST 2017
	 */
	public Double getBuyPrice() {
		return buyPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column quotation_sub_sheet.BUY_PRICE
	 *
	 * @param buyPrice
	 *            the value for quotation_sub_sheet.BUY_PRICE
	 *
	 * @mbg.generated Tue Jul 18 00:02:59 CST 2017
	 */
	public void setBuyPrice(Double buyPrice) {
		this.buyPrice = buyPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column quotation_sub_sheet.UNIT
	 *
	 * @return the value of quotation_sub_sheet.UNIT
	 *
	 * @mbg.generated Tue Jul 18 00:02:59 CST 2017
	 */
	public String getUnit() {
		return unit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column quotation_sub_sheet.UNIT
	 *
	 * @param unit
	 *            the value for quotation_sub_sheet.UNIT
	 *
	 * @mbg.generated Tue Jul 18 00:02:59 CST 2017
	 */
	public void setUnit(String unit) {
		this.unit = unit == null ? null : unit.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column quotation_sub_sheet.WEIGHT
	 *
	 * @return the value of quotation_sub_sheet.WEIGHT
	 *
	 * @mbg.generated Tue Jul 18 00:02:59 CST 2017
	 */
	public Integer getWeight() {
		return weight;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column quotation_sub_sheet.WEIGHT
	 *
	 * @param weight
	 *            the value for quotation_sub_sheet.WEIGHT
	 *
	 * @mbg.generated Tue Jul 18 00:02:59 CST 2017
	 */
	public void setWeight(Integer weight) {
		this.weight = weight;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column quotation_sub_sheet.VOLUME
	 *
	 * @return the value of quotation_sub_sheet.VOLUME
	 *
	 * @mbg.generated Tue Jul 18 00:02:59 CST 2017
	 */
	public Integer getVolume() {
		return volume;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column quotation_sub_sheet.VOLUME
	 *
	 * @param volume
	 *            the value for quotation_sub_sheet.VOLUME
	 *
	 * @mbg.generated Tue Jul 18 00:02:59 CST 2017
	 */
	public void setVolume(Integer volume) {
		this.volume = volume;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column quotation_sub_sheet.TOP
	 *
	 * @return the value of quotation_sub_sheet.TOP
	 *
	 * @mbg.generated Tue Jul 18 00:02:59 CST 2017
	 */
	public Long getTop() {
		return top;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column quotation_sub_sheet.TOP
	 *
	 * @param top
	 *            the value for quotation_sub_sheet.TOP
	 *
	 * @mbg.generated Tue Jul 18 00:02:59 CST 2017
	 */
	public void setTop(Long top) {
		this.top = top;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column quotation_sub_sheet.BOTTOM
	 *
	 * @return the value of quotation_sub_sheet.BOTTOM
	 *
	 * @mbg.generated Tue Jul 18 00:02:59 CST 2017
	 */
	public Long getBottom() {
		return bottom;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column quotation_sub_sheet.BOTTOM
	 *
	 * @param bottom
	 *            the value for quotation_sub_sheet.BOTTOM
	 *
	 * @mbg.generated Tue Jul 18 00:02:59 CST 2017
	 */
	public void setBottom(Long bottom) {
		this.bottom = bottom;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column quotation_sub_sheet.HEIGHT
	 *
	 * @return the value of quotation_sub_sheet.HEIGHT
	 *
	 * @mbg.generated Tue Jul 18 00:02:59 CST 2017
	 */
	public Long getHeight() {
		return height;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column quotation_sub_sheet.HEIGHT
	 *
	 * @param height
	 *            the value for quotation_sub_sheet.HEIGHT
	 *
	 * @mbg.generated Tue Jul 18 00:02:59 CST 2017
	 */
	public void setHeight(Long height) {
		this.height = height;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column quotation_sub_sheet.PACKING
	 *
	 * @return the value of quotation_sub_sheet.PACKING
	 *
	 * @mbg.generated Tue Jul 18 00:02:59 CST 2017
	 */
	public String getPacking() {
		return packing;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column quotation_sub_sheet.PACKING
	 *
	 * @param packing
	 *            the value for quotation_sub_sheet.PACKING
	 *
	 * @mbg.generated Tue Jul 18 00:02:59 CST 2017
	 */
	public void setPacking(String packing) {
		this.packing = packing == null ? null : packing.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column quotation_sub_sheet.PACKING_RATE
	 *
	 * @return the value of quotation_sub_sheet.PACKING_RATE
	 *
	 * @mbg.generated Tue Jul 18 00:02:59 CST 2017
	 */
	public Double getPackingRate() {
		return packingRate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column quotation_sub_sheet.PACKING_RATE
	 *
	 * @param packingRate
	 *            the value for quotation_sub_sheet.PACKING_RATE
	 *
	 * @mbg.generated Tue Jul 18 00:02:59 CST 2017
	 */
	public void setPackingRate(Double packingRate) {
		this.packingRate = packingRate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column quotation_sub_sheet.NUMBER
	 *
	 * @return the value of quotation_sub_sheet.NUMBER
	 *
	 * @mbg.generated Tue Jul 18 00:02:59 CST 2017
	 */
	public Integer getNumber() {
		return number;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column quotation_sub_sheet.NUMBER
	 *
	 * @param number
	 *            the value for quotation_sub_sheet.NUMBER
	 *
	 * @mbg.generated Tue Jul 18 00:02:59 CST 2017
	 */
	public void setNumber(Integer number) {
		this.number = number;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column quotation_sub_sheet.PACK_NUM
	 *
	 * @return the value of quotation_sub_sheet.PACK_NUM
	 *
	 * @mbg.generated Tue Jul 18 00:02:59 CST 2017
	 */
	public Integer getPackNum() {
		return packNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column quotation_sub_sheet.PACK_NUM
	 *
	 * @param packNum
	 *            the value for quotation_sub_sheet.PACK_NUM
	 *
	 * @mbg.generated Tue Jul 18 00:02:59 CST 2017
	 */
	public void setPackNum(Integer packNum) {
		this.packNum = packNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column quotation_sub_sheet.TOTALCBM
	 *
	 * @return the value of quotation_sub_sheet.TOTALCBM
	 *
	 * @mbg.generated Tue Jul 18 00:02:59 CST 2017
	 */
	public Double getTotalcbm() {
		return totalcbm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column quotation_sub_sheet.TOTALCBM
	 *
	 * @param totalcbm
	 *            the value for quotation_sub_sheet.TOTALCBM
	 *
	 * @mbg.generated Tue Jul 18 00:02:59 CST 2017
	 */
	public void setTotalcbm(Double totalcbm) {
		this.totalcbm = totalcbm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column quotation_sub_sheet.GW
	 *
	 * @return the value of quotation_sub_sheet.GW
	 *
	 * @mbg.generated Tue Jul 18 00:02:59 CST 2017
	 */
	public Double getGw() {
		return gw;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column quotation_sub_sheet.GW
	 *
	 * @param gw
	 *            the value for quotation_sub_sheet.GW
	 *
	 * @mbg.generated Tue Jul 18 00:02:59 CST 2017
	 */
	public void setGw(Double gw) {
		this.gw = gw;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column quotation_sub_sheet.TOTAL_GW
	 *
	 * @return the value of quotation_sub_sheet.TOTAL_GW
	 *
	 * @mbg.generated Tue Jul 18 00:02:59 CST 2017
	 */
	public Double getTotalGw() {
		return totalGw;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column quotation_sub_sheet.TOTAL_GW
	 *
	 * @param totalGw
	 *            the value for quotation_sub_sheet.TOTAL_GW
	 *
	 * @mbg.generated Tue Jul 18 00:02:59 CST 2017
	 */
	public void setTotalGw(Double totalGw) {
		this.totalGw = totalGw;
	}
}